### ISSUE TITLE
tap_action stopped working

### ISSUE THREAD

**Issue by 03397** [maxwroc/battery-state-card#57]
**Describe the bug**
The tap_action stopped working in one of the last 2-3 upgrades. I have pinpointed this at the latest version. 

**How to reproduce**
Steps to reproduce the behavior.

**Expected behavior**

**YAML configuration**
```yaml
# please paste here your card config
color_gradient:
  - '#ff0000'
  - '#ffff00'
  - '#00ff00'
entities:
  - entity: sensor.aeotec_zw129_wallmote_duo_battery_level_2
  - entity: sensor.aeotec_zw129_wallmote_duo_battery_level_3
  - entity: sensor.aeon_labs_zw130_wallmote_quad_battery_level
  - entity: sensor.aeotec_zwa003_nanomote_quad_battery_level
name: Recharchable Batteries
tap_action:
  action: more-info
type: 'custom:battery-state-card'
```

**Screenshots**
When I click I am getting this error message
https://xxxx.xxxxx.xxxx.xxx:yyyyy/hacsfiles/battery-state-card/battery-state-card.js:37:939 Uncaught TypeError: t.card.dispatchEvent is not a function

**Version**
What is the version of the card?
1.3.2

**Comment by maxwroc** [comment]
Fixed in v1.3.3

**Comment by 03397** [comment]
@maxwroc 
The fix is not always working. I do not know if this is related with the front end changes or with cache.
After I have upgraded to 0.110.1 and this to 1.3.3 the was still getting this error message below when I tapped on. After several refreshes the problem disappeared.  When I restart my whole device that runs home assistant the problem appeared again with the same error message. Again, after several refreshes the problem dissapered.
Logger: frontend.js.latest.202005191
Source: components/system_log/__init__.py:209
First occurred: 11:33:13 AM (6 occurrences)
Last logged: 11:33:19 AM

https://nicolaspc.ddnsfree.com:8123/hacsfiles/battery-state-card/battery-state-card.js:37:939 Uncaught TypeError: t.card.dispatchEvent is not a function

**Comment by maxwroc** [comment]
I think that the card code is for some reason taken from browser cache. My suggestion is to update the resource url (in your ui-lovelace.yaml) to force refresh e.g.

```yaml
  - url: /hacsfiles/battery-state-card/battery-state-card.js?v=1.3.3
    type: module
```

Note the part **`?v=1.3.3`**

**Comment by maxwroc** [comment]
If you have a browser with developer console (shown after hitting F12) please check which card version is logged there:
![image](https://user-images.githubusercontent.com/8268674/82653975-eb0e8680-9c17-11ea-8eed-4d15adb25ed2.png)

**Comment by 03397** [comment]
I did that and It shows 1.3.4 but after I changed the URL. I keep track on this and I will let you know of the problem are reappears.

Thanks

________________________________
