### ISSUE TITLE
filtering by entity_id with wildcard won't filter out all the entities

### ISSUE THREAD

**Issue by marcgarciamarti** [maxwroc/battery-state-card#74]
It may be my mistake but when I try to filter out entities based on their entity_id, not all of them are filtered out

configure exclusion as per the documentation

remove entities matching the wildcard defined

**YAML configuration**
```
bulk_rename:
  - from: /_battery$/
filter:
  exclude:
    - name: entity_id
      value: mqtt
      operator: contains
    - name: entity_id
      value: phone
      operator: contains
  include:
    - name: attributes.device_class
      value: battery
secondary_info: last_seen
sort_by_level: asc
title: Baterías
type: 'custom:battery-state-card'
```

![Screen Shot 2020-06-07 at 13 37 01](https://user-images.githubusercontent.com/12695572/83967675-0b9b3980-a8c4-11ea-91a2-02086eda6b8c.png)

**Version**
  v1.3.6

**Comment by maxwroc** [comment]
Please give an example of id which was not filtered out. E.g. in secondary info put entity_id and it should be printed there (paste another screenshot)

**Comment by marcgarciamarti** [comment]
> Please give an example of id which was not filtered out. E.g. in secondary info put entity_id and it should be printed there (paste another screenshot)

here you go

![Screen Shot 2020-06-07 at 13 49 56](https://user-images.githubusercontent.com/12695572/83967954-e27ba880-a8c5-11ea-8006-8866fdb9f839.png)

most of the cases that I thought were matching this case were not but this example above is.

Now that I see the result after activating the secondary information, may I ask you to help me filter out entities by their friendly name instead? I spent a couple of hours trying to do so but I couldn't and ended up gaving up and taking the entity_id route...

thanks a million

**Comment by maxwroc** [comment]
Fixed in 1.3.7

**Comment by marcgarciamarti** [comment]
Hi @maxwroc , tested the new version but it still won't filter out that example above.

On a similar note, I asked you earlier if could you help me filter out entities based on their friendly name instead? I spent a couple of hours trying to do so but I couldn't and ended up gaving up and taking the entity_id route...

**Comment by maxwroc** [comment]
Have you tried something like the following:
```yaml
filter:
  exclude:
    - name: attributes.friendly_name
      operator: contains
      value: "kitus"
    - name: attributes.friendly_name
      operator: contains
      value: "iPad de Marc"
    - name: attributes.friendly_name
      operator: contains
      value: "Lauris"
    - name: attributes.friendly_name
      operator: contains
      value: "iPad comedor"
```

Please keep in mind that this is case sensitive so lower/upper case letter matters.

To find out what is the state value and what are available attributes go to Developer Tools > States

![image](https://user-images.githubusercontent.com/8268674/84446543-a3d74c80-ac3d-11ea-9e06-6a5e299d4b16.png)
